/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package manips.ihm;

import java.util.Observable;
import java.util.Observer;
import manips.Partie;

/**
 *
 * @author PaulPark
 */
public class SyntaxPanel extends javax.swing.JPanel implements Observer{
    private Partie partie;
    /**
     * Creates new form SyntaxPanel
     */
    public SyntaxPanel(Partie partie) {
        initComponents();
        this.partie = partie;
        partie.addObserver(SyntaxPanel.this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nbCoupsLabel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        nbLabel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        scoreALabel = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        scoreBLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jLabel8.setText("Nb de coups:");

        nbLabel.setText("0");

        jLabel10.setText("Score de A:");

        scoreALabel.setText("0.0");

        jLabel12.setText("Score de B:");

        scoreBLabel.setText("0.0");

        javax.swing.GroupLayout nbCoupsLabelLayout = new javax.swing.GroupLayout(nbCoupsLabel);
        nbCoupsLabel.setLayout(nbCoupsLabelLayout);
        nbCoupsLabelLayout.setHorizontalGroup(
            nbCoupsLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nbCoupsLabelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(nbCoupsLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12))
                .addGap(31, 31, 31)
                .addGroup(nbCoupsLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scoreBLabel)
                    .addComponent(scoreALabel)
                    .addComponent(nbLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        nbCoupsLabelLayout.setVerticalGroup(
            nbCoupsLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nbCoupsLabelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(nbCoupsLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(nbLabel))
                .addGap(18, 18, 18)
                .addGroup(nbCoupsLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(scoreALabel))
                .addGap(18, 18, 18)
                .addGroup(nbCoupsLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(scoreBLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setText("Synthèse");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nbCoupsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nbCoupsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel nbCoupsLabel;
    private javax.swing.JLabel nbLabel;
    private javax.swing.JLabel scoreALabel;
    private javax.swing.JLabel scoreBLabel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        nbLabel.setText(partie.getNbCoups()+"");
        scoreALabel.setText(partie.getScoreA()+"");
        scoreBLabel.setText(partie.getScoreB()+"");
    }
}
